artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://datasetsjp.s3.ca-central-1.amazonaws.com/Brain_Tumor_Datasets.zip?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjENL%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDGNhLWNlbnRyYWwtMSJHMEUCIQDStcDNR4KPTPxBHd3%2FDiAMioDX25RiHMhCDp%2BWXpdfhwIgLpqavVUyB7L0TfgyPzzMiGcgtCzgY39NYSwgH5WCgngq5AIIbBAAGgw5NzUwNTAwNDIzMDAiDHAoiHbpPwVf7jBMXSrBAracbNN2hfPAKzHBBBloPQFwoIOzmh5TBSMng8u9ZkxcS18KfYvRR4xNf2FCpN5uy7z2rePxj%2BDT98ptvDWyFDBKKSeu8CkRNRQGUdQkqO0Zqip%2FHzg%2BA0hIgKIiaFqVYlgfWli%2F%2B8%2FvBgMRYfpGN0TEMLWGJqRszFGPvUqy7KETPZVDb7sBRobkqOwLk2J6pw3%2FvyO%2BX50yfal%2F8pfpZOToyuMgFA%2B6fyJv1gyHDpMQMtG8ddC2whNz30wyYB8pzC2RZK8qnRR7%2B%2FlyCG%2BroczFpH3gxmXQN2f%2B%2BlXyon2FvhY7%2BkalfUSjTDTigSC%2F5VzT9G15eavgn4YQFhojqyGx7VtrHZIRsjN3Ci1GTwUrjys1IqaEfvWd82vO8wMCrkimqvPDdYfc9XqCN01V%2FXAbg2JvMZPdSG%2B4EqI1xBNCFDDWj6SzBjqzAu1Z8Hgfsc8PTO2UvKaYyMaq9rMIqhFn55DXdAiFn3itodjQJQ8dzc0betioahuB14UjkJgYychpKR89uEBL%2Fe6aaMHD1GxfC8O91gLaDJohxCaHbuZNxaIzJmYPLtukH1fnteOIUQj6vI%2BkNvdZCuC7vufVUJOcCdOiqr6uj90gypV8UUqo2yGr2F3FwY%2FITlkaVwbZMd3NbitCPgD0kiP1oq6%2Bdn9kxAUqkhBRciXc9N%2FENuTX27SH6%2BuTXZfRIA1jYhwBvJegqfcOgHb8TnRhGOQXashG4IxolO3ZnDzruYRGGDCPo0cfanWi6L4wcQYi9%2BmVJCflDbLPbzurYhzHsowTcABq%2F%2Bu%2FzFhiG%2FAwqibtmcIE0O35IGQLC6fGwtED9IcPiYVxkYS%2Fl4d4Z2x0eRw%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240612T022917Z&X-Amz-SignedHeaders=host&X-Amz-Expires=43200&X-Amz-Credential=ASIA6GBMC5O6AGJF2I7Y%2F20240612%2Fca-central-1%2Fs3%2Faws4_request&X-Amz-Signature=716a088533c6523b39e13001e10792d97cb0a6822253ed99d4658aa3a6e1fcad 
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5