artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://datasetsjp.s3.ca-central-1.amazonaws.com/Brain_Tumor_Datasets.zip?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEP7%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDGNhLWNlbnRyYWwtMSJHMEUCIAgmTJr4rlGlAaJxqhek4VQn72lGRbFrYWgRuN8%2Fno3YAiEA7fMxxovxJHiRnOeT8cVShhTxx%2FfTuFYdo%2FGBrcHY2Msq7QIIl%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAAGgw5NzUwNTAwNDIzMDAiDA5q8QXkaE00mdDuMCrBAvHEH1SDsqMo%2FVdCKDbLhjlbTdfmoXrhhZc6SpH983Wzyp1D%2FJxEl75HXpbRXmCB2U3858OQk%2BzVrKp%2Bhlj9ZoeJS9pI53BVqWKDYpBbnhWp2Bas0lrNjdCy3AsiVUKNyaLMYx%2BlQ%2BHfi4jn%2FknD5Vht%2BrWEzbvd892wg6NB1LEi8Yb%2BzyfOJokHmLMFTYgzL8AYn9QzADKCJEe5mSBH66sySiWrc3IAQHkqzNgddXWAvSeFx3g%2F9RHY%2B1Pn4%2Bi6CngYLNpLKqRHiKs5vN3t%2FwD2sGi%2FRnwrs3dbQrj2h4jfaeL1uSbOqlkuQiftOUj1lnyV90SLQQd9Go3FETLS4d7Hm99EGxuHCW304VhLCMkQufdCoFnDWQggiAbVQr6qARiSwJhFko082DxS1J1g0PCu27DvZuFOsvQa087BURJQMTDc3q2zBjqzAmezHxhnsA%2FCDCEHevoINlOzG7Ma6GmhKtm8ZjFMIYWY%2Bf60IE%2BSnGJvhTPojS31WMYWknky8xt2msZwdxZQ%2FOQeNzEojKFl5J4yYqaWOGLJ8ByEt8Awn1B2129nZ4BiIw8y3Xql%2FdfV5oX1%2BFP6EQWIhUfB5Fgjiyr33hzP%2Fn%2FBlS2ec8GkstyAOGE8SNxiwY2wx9mv6g1KbZiazYPXwKC1DQ2XmnkKc6ZlyMN5ikXK5VrOX5XJYKg8aMUIz17pYhHvj7ImDVVJuMdW5jju1bNnNVdptFuUvf%2FbK9YRu05J28qZ4BdH8Mf11LzFWrj54VqBGP66l5K0Y5nEsFIfc6K1HSOxAYO%2FbZoza93Rm35Di2dji2T0cdejHux40U5rpsyYf71g3cZKP7c0IdqCUfPA2E0%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240613T223145Z&X-Amz-SignedHeaders=host&X-Amz-Expires=43200&X-Amz-Credential=ASIA6GBMC5O6KJDUHIF3%2F20240613%2Fca-central-1%2Fs3%2Faws4_request&X-Amz-Signature=86166174ff6e3a073c427b2e70e710a14ecb68aad885db45dab4758486fa0852
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5